"""locations and readings

Revision ID: 36abdc5396ab
Revises: 
Create Date: 2026-09-12 23:52:41.049779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '36abdc5396ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(), nullable=False),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_station_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: no op.create_index() for the geometry GiST index here -- GeoAlchemy2
    # creates it itself via a DDL event fired on table creation. Autogenerate
    # proposes it too (a known gotcha, see database-build-guide.md Phase 8);
    # adding it again raises DuplicateTable.
    op.create_table('aqi_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('main_pollutant', sa.String(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('owm_aqi_index', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reliability_status', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aqi_readings')
    # index dropped automatically when the table is dropped below
    op.drop_table('locations')
    # ### end Alembic commands ###
