"""composite index on aqi_readings

Revision ID: f2db93fe6f5b
Revises: 8fbe7d5c64fc
Create Date: 2026-09-13 07:26:19.519409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2db93fe6f5b'
down_revision: Union[str, Sequence[str], None] = '8fbe7d5c64fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_aqi_readings_location_recorded', 'aqi_readings', ['location_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aqi_readings_location_recorded', table_name='aqi_readings')
    # ### end Alembic commands ###
